name: dartevel_cli
version: 0.0.0
description: cli
repository: https://github.com/dartevel/framework

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.2.0  
  path: ^1.8.0
  http: ^0.13.3
  io: ^1.0.3  

  
dev_dependencies:
  test: ">=1.15.0 <2.0.0"

executables: 
  dartevel: dartevel
